### ISSUE TITLE
🚑  Basic usage fully crashes the nodeJS app

### ISSUE THREAD

**Issue by a-tokyo** [Underscoretec/multer-s3-rotate#1]
Attempting to use the examples in the Readme results in the following error:

```
    storage.getResize.bind(storage, req, file),
                      ^
TypeError: storage.getResize.bind is not a function
    at collect (/Users/__PROJECTNAME__/node_modules/multer-s3-rotate/index.js:63:23)
    at S3Storage._handleFile (/Users/__PROJECTNAME__/node_modules/multer-s3-rotate/index.js:181:3)
    at StorageEngine._handleFile (/Users/__PROJECTNAME__/src/utils/multer/Storage.js:45:20)
    at cb (/Users/__PROJECTNAME__/node_modules/multer/lib/make-middleware.js:144:17)
    at fileFilter (/Users/__PROJECTNAME__/src/utils/multer/utils.js:89:12)
    at wrappedFileFilter (/Users/__PROJECTNAME__/node_modules/multer/index.js:44:7)
    at Busboy.<anonymous> (/Users/__PROJECTNAME__/node_modules/multer/lib/make-middleware.js:114:7)
    at Busboy.emit (events.js:209:13)
    at Busboy.EventEmitter.emit (domain.js:476:20)
    at Busboy.emit (/Users/__PROJECTNAME__/node_modules/busboy/lib/main.js:38:33)
    at PartStream.<anonymous> (/Users/__PROJECTNAME__/node_modules/busboy/lib/types/multipart.js:213:13)
    at PartStream.emit (events.js:209:13)
    at PartStream.EventEmitter.emit (domain.js:476:20)
    at HeaderParser.<anonymous> (/Users/__PROJECTNAME__/node_modules/dicer/lib/Dicer.js:51:16)
    at HeaderParser.emit (events.js:209:13)
    at HeaderParser.EventEmitter.emit (domain.js:476:20)
    at HeaderParser._finish (/Users/__PROJECTNAME__/node_modules/dicer/lib/HeaderParser.js:68:8)
    at SBMH.<anonymous> (/Users/__PROJECTNAME__/node_modules/dicer/lib/HeaderParser.js:40:12)
    at SBMH.emit (events.js:209:13)
    at SBMH.EventEmitter.emit (domain.js:47)
```

How to replicate:
- Exactly apply the documented steps in the readme in a fully functioning project

**Comment by uplankita** [comment]
Thank you for the feedback, we have been a bit busy these days hence this module went to the back burner. We would be looking into it in the coming week. But again thanks for taking time to create this issue.

**Comment by a-tokyo** [comment]
Thanks for the response. I tried debugging it a bit but didn't seem to resolve the issue.
